# 声明一个命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: support
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: support
  name: app-gateway
data:
  application.yml: |-
    management:
      endpoints:
        web:
          exposure:
            include: info, health, metrics
      metrics:
        export:
          atlas:
            enabled: false
    server:
      port: 8080
    spring:
      application:
        name: app-gateway
      redis:
        host: redis.fawa1988
        port: 6379
        pool:
          database: 0
      cloud:
        gateway:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: '*'
                allowedMethods: '*'
                allowedHeaders: '*'
          routes:
            - id: app-demo-datasource
              uri: http://app-demo-datasource.demo:8080
              predicates:
              - Path=/support-demo-datasource/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"
                - name: Retry
                  args:
                    retries: 3
                    series:
                      - SERVER_ERROR
                    statuses:
                      - OK
                    methods:
                      - GET
                      - POST
                    exceptions:
                      - java.lang.RuntimeException
