# 声明一个命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: demo
  name: demo-datasource
data:
  application.yml: |-
    management:
      endpoints:
        web:
          exposure:
            include: info, health, metrics
      metrics:
        export:
          atlas:
            enabled: false
    server:
      # 服务端口
      port: 8080
    spring:
      application:
        name: demo-datasource
      servlet:
        multipart:
          max-file-size: 32MB
          max-request-size: 32MB
      amqp:
        host: amqp.blg
        username: guest
        password: guest
        port: 5672
      redis:
        host: redis.blg
        port: 6379
        pool:
          database: 0
      datasource:
        write:
          jdbc-url: jdbc:mysql://mysqldb.blg:3306/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
          username: demo_datasource_writer
          password: demo_datasource_writer
          maximum-pool-size: 100
        read:
          jdbc-url: jdbc:mysql://mysqldb.blg:3306/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
          username: demo_datasource_reader
          password: demo_datasource_reader
          maximum-pool-size: 100
      jpa:
        properties:
          hibernate:
            jdbc:
              fetch_size: 100
              batch_size: 50
            hbm2ddl:
              auto: update
            cache:
              use_second_level_cache: false
              use_query_cache: false
    ---
    management:
      endpoints:
        web:
          exposure:
            include: info, health, metrics
      metrics:
        export:
          atlas:
            enabled: false
    server:
      # 服务端口
      port: 8080
    spring:
      profiles: dev
      application:
        name: demo-datasource
      servlet:
        multipart:
          max-file-size: 32MB
          max-request-size: 32MB
      amqp:
        host: localhost
        username: guest
        password: guest
        port: 30120
      redis:
        host: localhost
        port: 30130
        pool:
          database: 0
      datasource:
        write:
          jdbc-url: jdbc:mysql://localhost:30110/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
          username: demo_datasource_writer
          password: demo_datasource_writer
          maximum-pool-size: 100
        read:
          jdbc-url: jdbc:mysql://localhost:30110/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
          username: demo_datasource_reader
          password: demo_datasource_reader
          maximum-pool-size: 100
      jpa:
        properties:
          hibernate:
            jdbc:
              fetch_size: 100
              batch_size: 50
            hbm2ddl:
              auto: update
            cache:
              use_second_level_cache: false
              use_query_cache: false