# 声明一个命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: demo
  name: app-demo-datasource
data:
  application.yml: |-
    management:
      endpoints:
        web:
          exposure:
            include: info, health, metrics
      metrics:
        export:
          atlas:
            enabled: false
    server:
      # 服务端口
      port: 8080
    spring:
      application:
        name: app-demo-datasource
      servlet:
        multipart:
          max-file-size: 32MB
          max-request-size: 32MB
      amqp:
        host: amqp.blg
        username: guest
        password: guest
        port: 5672
      redis:
        host: redis.blg
        port: 6379
        pool:
          database: 0
      datasource:
        url: jdbc:mysql://mysql.blg:3306/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
        username: demo-datasource-writer
        password: demo-datasource-writer
      jpa:
        database: mysql
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    ---
    management:
      endpoints:
        web:
          exposure:
            include: info, health, metrics
      metrics:
        export:
          atlas:
            enabled: false
    server:
      # 服务端口
      port: 8080
    spring:
      profiles: dev
      application:
        name: app-demo-datasource
      servlet:
        multipart:
          max-file-size: 32MB
          max-request-size: 32MB
      amqp:
        host: localhost
        username: guest
        password: guest
        port: 30120
      redis:
        host: localhost
        port: 30130
        pool:
          database: 0
      datasource:
        url: jdbc:mysql://localhost:30110/demo_datasource?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useFastDateParsing=false&pinGlobalTxToPhysicalConnection=true&serverTimezone=Hongkong
        username: root
        password: 123999
        driver-class-name: com.mysql.jdbc.Driver
      jpa:
        database: mysql
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        database-platform:
          org.hibernate.dialect.MySQLDialect