# Redis开始
apiVersion: v1
kind: Pod
metadata:
  namespace: blg
  name: redis
  labels:
    com.blg.service: redis
spec:
  containers:
  - image: redis
    imagePullPolicy: IfNotPresent
    name: redis
    ports:
    - containerPort: 6379
    resources:
      limits:
        memory: 0.5Gi
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: blg
  name: redis
  labels:
    com.blg.service: redis
spec:
  type: NodePort
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
    nodePort: 30130
  selector:
    com.blg.service: redis
