# MYSQL开始
# 声明一个PVC卷
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: blg
  name: mysql-pvc
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: blg
  name: mysqldb
  labels:
    com.blg.service: mysqldb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: "888888"
    image: mysql
    imagePullPolicy: IfNotPresent
    name: mysqldb
    args: ["--max_connections=10240"]
    ports:
    - containerPort: 3306
    resources:
      limits:
        memory: 1Gi
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-pvc
  restartPolicy: OnFailure
  volumes:
  - name: mysql-pvc
    persistentVolumeClaim:
      claimName: mysql-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: blg
  name: mysqldb
  labels:
    com.blg.service: mysqldb
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 30110
  selector:
    com.blg.service: mysqldb
